name: Renovate

on:
  schedule:
    # Run once a week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get token
        id: get-token
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: 3060316
          private-key: ${{ secrets.NGRENOVATE_PRIVATE_KEY }}
          owner: ngallegos
      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.6
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.get-token.outputs.token  }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }} 
